Update VersionLink.yml

diff --git a/.github/workflows/VersionLink.yml b/.github/workflows/VersionLink.yml
--- a/.github/workflows/VersionLink.yml
+++ b/.github/workflows/VersionLink.yml
@@ -61,8 +61,38 @@ jobs:
     - name: Import Component Into UCD
       run: |
         curl --insecure --request PUT 'https://10.134.119.250:8443/cli/component/integrate' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"component": "PdmComponent","properties": {"version": Comp1-1.2.3-${{ github.run_number }}-4.5.6,"description": ""}}'
+    - name: Install jq
+      run: |
+        wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
+        chmod +x jq
+        sudo mv jq /usr/local/bin/
+    - name: Run curl with loop and timeout
+      id: find_component_version
+      run: |
+        timeout_duration=600  # Set the timeout duration in seconds (e.g., 300 seconds = 5 minutes)
+        target_version_name="Comp1-1.2.3-${{ github.run_number }}-4.5.6"  # Replace with the specific version name you are looking for
+
+        end_time=$((SECONDS + timeout_duration))
+
+        while [ $SECONDS -lt $end_time ]; do
+          response=$(curl --insecure  --request GET 'https://10.134.119.250:8443/cli/component/versions?component=PdmComponent' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=')
+          version_names=$(echo "$response" | jq -r '.[].name')
+
+          if echo "$version_names" | grep -q "$target_version_name"; then
+            echo "Found version with name: $target_version_name"
+            echo "$response"  # Print the full response for the matching version (optional)
+            break
+          fi
+
+          sleep 10  # Adjust the sleep duration (in seconds) between each curl request
+        done
+
+        if [ $SECONDS -ge $end_time ]; then
+          echo "Timeout reached. Version with name $target_version_name not found."
+          exit 1
+        fi
     - name: Wait for 30s
-      run: sleep 60
+      run: sleep 30
     - name: Create Snapshot
       run: |
         curl --insecure --request PUT 'https://10.134.119.250:8443/cli/snapshot/createSnapshot' --header 'Content-Type: application/json' --header 'Authorization: Basic YWRtaW46YWRtaW4=' --data '{"name": July-2023-RC-${{ github.run_number }},"application": "PdmApp","description": "Some snapshot","versions": [{"PdmComponent": "latest"}]}'
